name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=book.pdf pages/stories/*.mdx
      - run: |
        git add .
        git commit -m "generated"
        git push
