name: Generate Book PDF
on:
  workflow_dispatch:
  schedule:
    # UTC
    - cron: '24 0 * * 1'
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
        with:
          cache-dependency-path: requirements.typ
      - run: typst compile main.typ
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: generate book'
