name: Generate Book PDF
on:
  workflow_dispatch:
  schedule:
    # UTC
    - cron: '24 0 * * 1'
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create file list
        id: files_list
        run: |
          echo "files=$(printf '"%s" ' $(ls pages/stories/*.md | grep -v index)" > $GITHUB_OUTPUT
      - uses: docker://pandoc/latex:3.6-ubuntu
        with:
          args: --output=book.pdf pages/stories/index.md ${{ steps.files_list.outputs.files }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: generate book'
