name: Write Wordcount
on:
  push:
    branches:
      - main
jobs:
  generateInputPaths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate matrix
        id: set-matrix
        run: |
          echo "matrix=$(printf '%s ' pages/stories/*.mdx | jq -R -s -c 'split(" ") | map(select(length > 0))')" > $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  pandoc:
    needs: generateInputPaths
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.generateInputPaths.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/latex:2.9
        with:
          args: --lua-filter ./wordcount.lua ${{ matrix.path }}
